builds:
  - main: ./cmd/cli/bip39.go
    binary: bip39
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X "main.version={{ .Version }}"
      - -X "main.commitID={{ .Commit }}"
      - -X "main.buildDate={{ .Date }}"
